# Imports and Setups

In [1]:
! pip install transformers==4.10.1

     |████████████████████████████████| 2.8 MB 5.1 MB/s 
     |████████████████████████████████| 880 kB 44.9 MB/s 
     |████████████████████████████████| 596 kB 47.5 MB/s 
     |████████████████████████████████| 84 kB 1.6 MB/s 
     |████████████████████████████████| 3.3 MB 19.4 MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895260 sha256=f25b07835850384381a0fc76af8f7bb966ef5b31563f515ce0227024627f3910
  Stored in directory: /root/.cache/pip/wheels/87/39/dd/a83eeef36d0bf98e7a4d1933a4ad2d660295a40613079bafc9
Successfully built sacremoses
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
! pip install nlpaug==1.1.7

     |████████████████████████████████| 405 kB 4.6 MB/s 


In [3]:
! pip install sentencepiece

     |████████████████████████████████| 1.2 MB 5.1 MB/s 


In [4]:
! pip install simpletransformers

     |████████████████████████████████| 249 kB 4.6 MB/s 
     |████████████████████████████████| 342 kB 63.4 MB/s 
     |████████████████████████████████| 1.8 MB 57.2 MB/s 
     |████████████████████████████████| 43 kB 2.3 MB/s 
     |████████████████████████████████| 10.1 MB 50.5 MB/s 
     |████████████████████████████████| 181 kB 63.2 MB/s 
     |████████████████████████████████| 145 kB 63.1 MB/s 
     |████████████████████████████████| 63 kB 1.9 MB/s 
     |████████████████████████████████| 212 kB 66.3 MB/s 
     |████████████████████████████████| 136 kB 65.8 MB/s 
     |████████████████████████████████| 1.1 MB 56.4 MB/s 
     |████████████████████████████████| 127 kB 68.9 MB/s 
     |████████████████████████████████| 144 kB 63.2 MB/s 
     |████████████████████████████████| 94 kB 3.4 MB/s 
     |████████████████████████████████| 271 kB 42.3 MB/s 
     |████████████████████████████████| 4.3 MB 16.5 MB/s 
     |████████████████████████████████| 164 kB 43.6 MB/s 
     |██████████████

Lendo o Arquivo

In [1]:
from google.colab import drive
drive.mount('drive')

Drive already mounted at drive; to attempt to forcibly remount, call drive.mount("drive", force_remount=True).


In [2]:
import os
os.environ['WANDB_DISABLED'] = 'true'

In [3]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas()


In [ ]:
# import transformers

# transformers.logging.set_verbosity_info()

In [ ]:
dataset = pd.read_csv('/content/drive/My Drive/Colab Notebooks/semeval_ironic/SemEval2018-T3-train-taskA_emoji.txt',sep = '\t')
dataset.head()

Tweet index  Label                                         Tweet text
0            1      1  Sweet United Nations video. Just in time for C...
1            2      1  @mrdahl87 We are rumored to have talked to Erv...
2            3      1  Hey there! Nice to see you Minnesota/ND Winter...
3            4      0                3 episodes left I'm dying over here
4            5      1  I can't breathe! was chosen as the most notabl...

In [4]:
num_gen = 5
perc = 40

In [ ]:
X = dataset['Tweet text']
y = dataset['Label']

In [ ]:
base_cru_1p = dataset.copy()

Gerando Base Percentual

In [5]:
from sklearn.model_selection import train_test_split
X_resto, X_treino_1p, y_resto, y_treino_1p = train_test_split(X, y, stratify=y, test_size=(perc/100), random_state=42) # Selecionando 1%

NameError: ignored

In [ ]:
import pandas as pd

data = {'texto': X_treino_1p, 'label': y_treino_1p}
base_cru_1p = pd.DataFrame.from_dict(data)

In [ ]:
import pandas as pd

data = {'texto': X, 'label': y}
base_cru_1p = pd.DataFrame.from_dict(data)

In [ ]:
base_cru_1p.head()

texto  label
0  Sweet United Nations video. Just in time for C...      1
1  @mrdahl87 We are rumored to have talked to Erv...      1
2  Hey there! Nice to see you Minnesota/ND Winter...      1
3                3 episodes left I'm dying over here      0
4  I can't breathe! was chosen as the most notabl...      1

In [5]:
arq = '/content/drive/My Drive/Colab Notebooks/paper_asoc/perc_' +str(perc) + '/base_trec_'+str(perc)+'_original.csv'
base_cru_1p = pd.read_csv(arq, encoding='utf-8', sep=';', decimal = ',')

Só rodar quando gerar o original

# Treino Classificador

In [6]:
from simpletransformers.classification import ClassificationModel
import pandas as pd
import logging
import sklearn


In [7]:
train_df = base_cru_1p.copy()
train_df.head()

texto  label
0                          What is a fear of water ?      1
1              What is Dick Clark 's date of birth ?      4
2  What part did Benjamin Franklin play in the de...      3
3  What country and western singer is known as Th...      5
4                         What does e.g. stand for ?      2

In [8]:
train_df.rename(columns= {'texto':'text', 'label': 'labels'}, inplace=True)
train_df.head()

text  labels
0                          What is a fear of water ?       1
1              What is Dick Clark 's date of birth ?       4
2  What part did Benjamin Franklin play in the de...       3
3  What country and western singer is known as Th...       5
4                         What does e.g. stand for ?       2

In [9]:
train_df.shape

(546, 2)

In [9]:

# train_df = pd.DataFrame(X_train)
# train_df['target'] = y_train

# eval_df = pd.DataFrame(X_test)
# eval_df['target'] = y_test



# Create a ClassificationModel
classifica = ClassificationModel('bert', 'bert-base-uncased', num_labels=6, args={'num_train_epochs':4,
                                                                          'train_batch_size':32,
                                                                          'max_seq_length':64,
                                                                          #'silent':True,
                                                                        #  "fp16":False,
                                                                          'overwrite_output_dir': True}) 

# Train the model
classifica.train_model(train_df)
# result, model_outputs, wrong_predictions = model.eval_model(eval_df, acc=sklearn.metrics.accuracy_score,f1=f1_multiclass)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

  0%|          | 0/2181 [00:00<?, ?it/s]

Epoch:   0%|          | 0/4 [00:00<?, ?it/s]

Running Epoch 0 of 4:   0%|          | 0/69 [00:00<?, ?it/s]

Running Epoch 1 of 4:   0%|          | 0/69 [00:00<?, ?it/s]

Running Epoch 2 of 4:   0%|          | 0/69 [00:00<?, ?it/s]

Running Epoch 3 of 4:   0%|          | 0/69 [00:00<?, ?it/s]

(276, 0.7001819499916788)

In [10]:
test = classifica.predict(["How can i be a millionaire?"])[1]
test

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

array([[ 3.68164062, -0.80712891, -1.2578125 , -1.23046875, -0.40454102,
         0.07537842]])

In [11]:
import numpy as np
mx = np.max(test, axis=-1, keepdims=True)
mx
# array([[1002],
#        [   4]])

# array([[-1,  0],
#        [-1,  0]])
numerator = np.exp(test - mx)
denominator = np.sum(numerator, axis=-1, keepdims=True)
denominator
# array([[ 1.36787944],
#        [ 1.36787944]])
numerator/denominator

array([[0.934836  , 0.01050238, 0.00669203, 0.00687754, 0.0157083 ,
        0.02538374]])

In [12]:
import re
import json
# from sklearn.model_selection import train_test_split



def build_text_files(data_json, dest_path):
    f = open(dest_path, 'w')
    data = ''
    for texts in data_json['texto']:
        summary = str(texts).strip()
        summary = re.sub(r"\s", " ", summary)
        data += summary + "\n"
    f.write(data)




build_text_files(base_cru_1p,'train_dataset.txt')
# build_text_files(test,'test_dataset.txt')

# print("Train dataset length: "+str(len(texto)))
# print("Test dataset length: "+ str(len(test)))


In [13]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("gpt2")

In [14]:
from transformers import TextDataset,DataCollatorForLanguageModeling

train_path = 'train_dataset.txt'

def load_dataset(train_path,tokenizer):
    train_dataset = TextDataset(
          tokenizer=tokenizer,
          file_path=train_path,
          block_size=128)
     
    
    data_collator = DataCollatorForLanguageModeling(
        tokenizer=tokenizer, mlm=False,
    )
    return train_dataset,data_collator

train_dataset,data_collator = load_dataset(train_path,tokenizer)

/usr/local/lib/python3.7/dist-packages/transformers/data/datasets/language_modeling.py:58: FutureWarning: This dataset will be removed from the library soon, preprocessing should be handled with the 🤗 Datasets library. You can have a look at this example script for pointers: https://github.com/huggingface/transformers/blob/master/examples/pytorch/language-modeling/run_mlm.py
  FutureWarning,


In [15]:
from transformers import Trainer, TrainingArguments,AutoModelWithLMHead

model = AutoModelWithLMHead.from_pretrained("gpt2")


training_args = TrainingArguments(
    output_dir="./gpt2-model-10p", #The output directory
    overwrite_output_dir=True, #overwrite the content of the output directory
    num_train_epochs=30, # number of training epochs
    per_device_train_batch_size=32, # batch size for training
    per_device_eval_batch_size=64,  # batch size for evaluation
    # eval_steps = 400, # Number of update steps between two evaluations.
    # save_steps=800, # after # steps model is saved 
    # warmup_steps=500,# number of warmup steps for learning rate scheduler
    # prediction_loss_only=True,
    )


trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    # eval_dataset=test_dataset,
)

/usr/local/lib/python3.7/dist-packages/transformers/models/auto/modeling_auto.py:592: FutureWarning: The class `AutoModelWithLMHead` is deprecated and will be removed in a future version. Please use `AutoModelForCausalLM` for causal language models, `AutoModelForMaskedLM` for masked language models and `AutoModelForSeq2SeqLM` for encoder-decoder models.
  FutureWarning,
Using the `WAND_DISABLED` environment variable is deprecated and will be removed in v5. Use the --report_to flag to control the integrations used for logging result (for instance --report_to none).


In [16]:
trainer.train()

***** Running training *****
  Num examples = 268
  Num Epochs = 30
  Instantaneous batch size per device = 32
  Total train batch size (w. parallel, distributed & accumulation) = 32
  Gradient Accumulation steps = 1
  Total optimization steps = 270




Training completed. Do not forget to share your model on huggingface.co/models =)




TrainOutput(global_step=270, training_loss=2.4572243019386573, metrics={'train_runtime': 141.2255, 'train_samples_per_second': 56.93, 'train_steps_per_second': 1.912, 'total_flos': 525196984320000.0, 'train_loss': 2.4572243019386573, 'epoch': 30.0})

In [17]:
trainer.save_model()

Saving model checkpoint to ./gpt2-model-10p
Configuration saved in ./gpt2-model-10p/config.json
Model weights saved in ./gpt2-model-10p/pytorch_model.bin


In [18]:
from transformers import pipeline

tweet = pipeline('text-generation',model='./gpt2-model-10p', tokenizer='gpt2', device = 0)


loading configuration file ./gpt2-model-10p/config.json
Model config GPT2Config {
  "_name_or_path": "gpt2",
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "gradient_checkpointing": false,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "resid_pdrop": 0.1,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "torch_dtype": "float32",
  "transformers_version": "4.10.1",
  "use_cache": true,
  "vocab_size": 50257
}

loading configuration file ./gpt2-model-10p/config.json
M

In [19]:
tweet('What is', num_return_sequences = 5, max_length = 20)

Using pad_token, but it is not set yet.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "What is the word 'frivolousness '' in the title of an article in The New"},
 {'generated_text': "What is the most common infectious disease in Ireland ?\nWhat 's a real killer ?\nWhen"},
 {'generated_text': "What is the origin of the term `` thalassemia '' ?\nWhere are they located ?"},
 {'generated_text': 'What is the average time it takes one American to log 19 pounds of water in six weeks ?\n'},
 {'generated_text': 'What is the best-seller of 1984 by the Time Warner Company ?\nOn March 5 , ``'}]

In [20]:
def generate_lambada(texto, token, gerador, classe, classificador, palavras, limiar, num_text, device, max_len, limite):
  texto_curto = token.decode(token.encode(texto, return_tensors="pt").to(device)[0, :palavras])
  res = []
  i=0

  while len(res) < num_text and i < limite:
    gerado = gerador(texto_curto, max_length = max_len)[0]

    # print(gerado['generated_text'])

    predito = classificador.predict([gerado['generated_text'].split('\n')[0]])[1]

    mx = np.max(predito, axis=-1, keepdims=True)
    numerator = np.exp(predito - mx)
    denominator = np.sum(numerator, axis=-1, keepdims=True)

    soft = numerator/denominator

    prob = soft[0][classe]

    if prob >= limiar :
      res.append(gerado['generated_text'])
    i+=1
    
  return res




In [21]:
def generate_lambada_vez(texto, token, gerador, classe, classificador, palavras, limiar, num_text, device, max_len, limite):
  texto_curto = token.decode(token.encode(texto, return_tensors="pt").to(device)[0, :palavras])
  res = []
  i=0

  gerado = gerador(texto_curto, max_length = max_len,num_return_sequences = limite )

  while len(res) < num_text and i < limite:
    #gerado = gerador(texto_curto, max_length = max_len)[0]

    print(gerado)

    predito = classificador.predict([gerado[i]['generated_text'].split('\n')[0]])[1]

    mx = np.max(predito, axis=-1, keepdims=True)
    numerator = np.exp(predito - mx)
    denominator = np.sum(numerator, axis=-1, keepdims=True)

    soft = numerator/denominator

    prob = soft[0][classe]

    if prob >= limiar :
      res.append(gerado[i]['generated_text'].split('\n')[0])
    i+=1
    
  return res




In [22]:
def gera_gpt(texto, token, gerador, palavras, limite, device, max_len):
  texto_curto = token.decode(token.encode(texto, return_tensors="pt").to(device)[0, :palavras])
  res = []
  i=0

  gerado = gerador(texto_curto, max_length = max_len,num_return_sequences = limite )

  for ger in gerado:
    res.append(ger['generated_text'].split('\n')[0])
    
  return res




In [23]:
def prob_softmax(predito, classe):

  mx = np.max(predito, axis=-1, keepdims=True)
  numerator = np.exp(predito - mx)
  denominator = np.sum(numerator, axis=-1, keepdims=True)

  soft = numerator/denominator

  prob = soft[classe]
    
  return prob




# Gera LAMBADA

In [24]:
repeticoes = 1

In [25]:
#%%capture
exp_lambada = []

for i in range(repeticoes):
  limiar = 0.3
  base_cru_1p_lambada = base_cru_1p.copy()
  base_cru_1p_lambada['parafraseador'] = base_cru_1p_lambada.progress_apply(lambda x:gera_gpt( x.texto, tokenizer, tweet, 3,  7, 'cuda', 15), axis=1)
  base_cru_1p_lambada = base_cru_1p_lambada.explode('parafraseador').reset_index(drop=True)
  preds = classifica.predict(base_cru_1p_lambada['parafraseador'].to_list())[1]
  base_cru_1p_lambada['preds'] = [preds[i] for i in range(preds.shape[0])]
  base_cru_1p_lambada['prob_text'] = base_cru_1p_lambada.progress_apply(lambda x:prob_softmax( x.preds, x.label), axis=1)
  fim = base_cru_1p_lambada[base_cru_1p_lambada['prob_text']>= limiar].copy()


  exp_lambada.append(fim[['texto', 'label', 'parafraseador']].copy())

  arquivo = '/content/drive/My Drive/Colab Notebooks/paper_asoc/perc_' +str(perc) + '/base_trec_'+str(perc)+'_lambada'+str(i+1)+'.csv'
  exp_lambada[i].to_csv(arquivo, encoding='utf-8', index=False, sep=';', decimal = ',')


  0%|          | 0/2181 [00:00<?, ?it/s]Using pad_token, but it is not set yet.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 2/2181 [00:00<02:49, 12.83it/s]Using pad_token, but it is not set yet.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
Using pad_token, but it is not set yet.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 4/2181 [00:00<04:48,  7.55it/s]Using pad_token, but it is not set yet.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 5/2181 [00:00<05:07,  7.09it/s]Using pad_token, but it is not set yet.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 6/2181 [00:00<05:34,  6.51it/s]Using pad_token, but it is not set yet.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  0%|          | 7/2181 [00:01<05:38,  6.42it/s]Using pad_token, but it is not set yet.
Setting 

huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)


  0%|          | 0/15267 [00:00<?, ?it/s]

  0%|          | 0/1909 [00:00<?, ?it/s]

100%|██████████| 15267/15267 [00:01<00:00, 14077.44it/s]


In [26]:
exp_lambada[0].shape

(10431, 3)